---
site:
  title: Red Hat Developer Hub Workshop
  url: https://github.com/rmarting/rhdh-exercises.git
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    #- path: ./content/lib

runtime:
  cache_dir: ./.cache/antora

antora:
  extensions:
    - id: dev-mode
      require: ./content/lib/dev-mode.js
      enabled: true
      
output:
  dir: ./www
