---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-app
  title: Sample Application
  description: |
    An application for testing Backstage functionality.
  labels:
    tier: "3"
  tags:
    - test
    - js
    - demo
  annotations:
    gitlab.com/project-slug: team-a/sample-app
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: sample-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=sample-app'
spec:
  type: service
  owner: group:team-a
  lifecycle: production
  #system: sample-system
  providesApis:
    - sample-app
