---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-operator-kubernetes-og
  namespace: gitlab-system
spec:
  targetNamespaces:
    - gitlab-system
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
spec:
  name: gitlab-operator-kubernetes
  source: certified-operators
  sourceNamespace: openshift-marketplace
  channel: stable
  startingCSV: gitlab-operator-kubernetes.v2.5.1
  installPlanApproval: Automatic
