apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless-logic
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless-logic-og
  namespace: openshift-serverless-logic
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: logic-operator-rhel8
  namespace: openshift-serverless-logic
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: logic-operator-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: logic-operator-rhel8.v1.36.0
