---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-system-og
  namespace: gitlab-system
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-runner-operator
  namespace: gitlab-system
spec:
  channel: stable
  name: gitlab-runner-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
