---
kind: Secret
apiVersion: v1
metadata:
  name: my-backstage-psql-secret-developer-hub
  labels:
    app: my-backstage-psql-developer-hub
stringData:
  POSTGRESQL_ADMIN_PASSWORD: "password"
  POSTGRES_HOST: "my-backstage-psql-developer-hub.rhdh-gitlab.svc.cluster.local"
  POSTGRES_PORT: "5432"  
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
type: Opaque
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: my-backstage-psql-developer-hub
  labels:
    app: my-backstage-psql-developer-hub
spec:
  serviceName: backstage-psql-developer-hub
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  template:
    metadata:
      labels:
        app: my-backstage-psql-developer-hub
    spec:
      restartPolicy: Always
      serviceAccountName: default
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: postgresql
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
              ephemeral-storage: 100Mi              
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - '-e'
                - |
                  exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log          
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - 'exec pg_isready -U ${POSTGRES_USER} -h 127.0.0.1 -p 5432'
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: POSTGRESQL_PORT_NUMBER
              value: '5432'
            - name: POSTGRESQL_VOLUME_DIR
              value: /var/lib/pgsql/data
            - name: PGDATA
              value: /var/lib/pgsql/data/userdata
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: '400'
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsGroup: 0
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: tcp-postgresql
              containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /var/lib/pgsql/data
          terminationMessagePolicy: File
          envFrom:
            - secretRef:
                name: my-backstage-psql-secret-developer-hub
          image: 'registry.redhat.io/rhel9/postgresql-15@sha256:ce71be9b4c01da3dec635c0c6cd40b117671b01271669f242998f6725e92c7e2'
      automountServiceAccountToken: false
      serviceAccount: default
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      dnsPolicy: ClusterFirst
  podManagementPolicy: OrderedReady
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: my-backstage-psql-developer-hub
---
kind: Service
apiVersion: v1
metadata:
  name: my-backstage-psql-developer-hub
  labels:
    app: my-backstage-psql-developer-hub
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster  
  selector:
    app: my-backstage-psql-developer-hub
