kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    # Admin Role
    # Catalog permissions
    p, role:default/admins, catalog.entity.read, read, allow
    p, role:default/admins, catalog.entity.create, create, allow
    p, role:default/admins, catalog.entity.refresh, update, allow
    p, role:default/admins, catalog.entity.delete, delete, allow
    p, role:default/admins, catalog.location.read, read, allow
    p, role:default/admins, catalog.location.create, create, allow
    p, role:default/admins, catalog.location.delete, delete, allow
    # Import permissions
    p, role:default/admins, bulk.import, use, allow
    # Scaffolder permissions
    p, role:default/admins, scaffolder.action.execute, use, allow
    p, role:default/admins, scaffolder.template.parameter.read, read, allow
    p, role:default/admins, scaffolder.template.step.read, read, allow
    p, role:default/admins, scaffolder.task.create, create, allow
    p, role:default/admins, scaffolder.task.cancel, use, allow
    p, role:default/admins, scaffolder.task.read, read, allow
    # RBAC permissions
    p, role:default/admins, policy.entity.read, read, allow
    p, role:default/admins, policy.entity.create, create, allow
    p, role:default/admins, policy.entity.update, update, allow
    p, role:default/admins, policy.entity.delete, delete, allow
    # Kubernetes permissions
    p, role:default/admins, kubernetes.proxy, use, allow
    # OCM permissions
    p, role:default/admins, ocm.entity.read, read, allow
    p, role:default/admins, ocm.cluster.read, read, allow
    # Topology permissions
    p, role:default/admins, topology.view.read, read, allow

    # Admin User
    # this is not needed now with the new superUser setting
    #g, user:default/1, role:default/admins

    # Team-A Role
    # Catalog permissions
    p, role:default/team-a, catalog.entity.read, read, allow
    p, role:default/team-a, catalog.entity.create, create, allow
    p, role:default/team-a, catalog.entity.refresh, update, allow
    p, role:default/team-a, catalog.entity.delete, delete, allow
    p, role:default/team-a, catalog.location.read, read, allow
    p, role:default/team-a, catalog.location.create, create, allow
    p, role:default/team-a, catalog.location.delete, delete, allow
    # Import permissions
    p, role:default/team-a, bulk.import, use, allow
    # Scaffolder permissions
    p, role:default/team-a, scaffolder.action.execute, use, allow
    p, role:default/team-a, scaffolder.template.parameter.read, read, allow
    p, role:default/team-a, scaffolder.template.step.read, read, allow
    p, role:default/team-a, scaffolder.task.create, create, allow
    p, role:default/team-a, scaffolder.task.cancel, use, allow
    p, role:default/team-a, scaffolder.task.read, read, allow
    # RBAC permissions
    p, role:default/team-a, policy.entity.read, read, allow
    p, role:default/team-a, policy.entity.create, create, allow
    p, role:default/team-a, policy.entity.update, update, allow
    p, role:default/team-a, policy.entity.delete, delete, allow
    # Kubernetes permissions
    #p, role:default/team-a, kubernetes.proxy, use, allow
    # OCM permissions
    #p, role:default/team-a, ocm.entity.read, read, allow
    #p, role:default/team-a, ocm.cluster.read, read, allow
    # Topology permissions
    #p, role:default/team-a, topology.view.read, read, allow

    # Team-B Role
    p, role:default/team-b, catalog.entity.read, read, deny

    # Groups
    g, group:default/team-a, role:default/team-a
    g, group:default/team-b, role:default/team-b

    # Users - Required until the GitLab resolvers match properly the users
    #g, user:default/2, role:default/team-a
    #g, user:default/3, role:default/team-b
