kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic'
        disabled: false
      # GitLab Plugins
      - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/immobiliarelabs-backstage-plugin-gitlab:bs_1.49.4__7.0.1!immobiliarelabs-backstage-plugin-gitlab'
        integrity: 'sha256:9f758d985ae10c0c9a65931c0dd29c15886315305f3a0fb839517d91761a133f'
        disabled: false
      - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/immobiliarelabs-backstage-plugin-gitlab-backend:bs_1.49.4__7.0.1!immobiliarelabs-backstage-plugin-gitlab-backend'
        integrity: 'sha256:3d31c16b31c491c42620e9e2172ef26d7f9bfcc4056152f82a5658907bc8ce6a'
        disabled: false
      # GitLab Organization Discovery
      - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-org-dynamic'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-community-plugin-rbac'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic'
        disabled: false
