apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: developer-hub
spec:
  deployment:
    patch:
      spec:
        replicas: 1 # Scaled down to avoid too many clients error - Review FAQ.
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
        #strategy:
        #  #rollingUpdate: null
        #  rollingUpdate:
        #    $patch: delete
        #  type: Recreate                            
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
        - name: lightspeed-app-config
    extraFiles:
      mountPath: /opt/app-root/src/rbac
      configMaps:
        - name: rbac-policy
        - name: lightspeed-stack
          mountPath: /app-root
          key: lightspeed-stack.yaml
          containers:
            - lightspeed-core        
    extraEnvs:
      envs:
        # Disabling TLS verification
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
          containers:
            - '*'
      configMaps:
        - name: rhdh-techdocs-bucket-claim
      secrets:
        - name: gitlab-secrets
        - name: rhdh-secrets
        - name: rhdh-techdocs-bucket-claim
        - name: backstage-psql-secret-developer-hub
          containers:
            - '*'
        - name: rhdh-lightspeed-auth-secrets
          containers:
            - lightspeed-core
    route:
      enabled: true
  database:
    enableLocalDb: true
  monitoring:
    enabled: true
  flavours:
    - name: lightspeed
      enabled: true
